---
############################################################
# post role tasks for windows role
############################################################

- name: Remove download directory
  win_file:
    path: "{{ common_download_path }}"
    state: absent
  when:
    - common_delete_download_path
  tags:
    - common
    - common.post
    - common.post.downloaddir
    - common.install
    - common.install.software
...